import = [ "~/AppData/Roaming/alacritty/schemes/orangetree.toml" ]

[window]
dimensions = { columns = 113, lines = 25 }
padding = { x = 20, y = 20 }

[scrolling]
history = 100000

[font]
normal = { family = "Cascadia Code PL", style = "SemiBold" }
size = 9.5
offset.y = 2
glyph_offset.y = 1

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[shell]
program = "wsl.exe"

[keyboard]
bindings = [
	{ key = "T", mods = "Control", action = "CreateNewWindow" }
]
