import = [ "~/.config/alacritty/schemes/orangetree.toml" ]

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 20, y = 20 }

[scrolling]
history = 100000

[font]
normal = { family = "Cascadia Code PL", style = "SemiBold" }
size = 14.0
offset.y = 2
glyph_offset.y = 1

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
	{ key = "T",      mods = "Command", action = "CreateNewWindow" },
	{ key = "Return", mods = "Command", action = "ToggleFullscreen" },
]
